#!/usr/bin/env bash
# This script changes the localhost and facebook.com

sudo cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
