#!/usr/bin/env bash
# Run Nginx as nginx user
pkill -f apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
-u nginx service nginx restart
